# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calculate_allele_spectrum_cpp <- function(input_population, markers, progress_bar) {
    .Call('_GenomeAdmixR_calculate_allele_spectrum_cpp', PACKAGE = 'GenomeAdmixR', input_population, markers, progress_bar)
}

simulate_cpp <- function(input_population, select, pop_size, number_of_founders, starting_proportions, total_runtime, morgan, progress_bar, track_frequency, track_markers, track_junctions, multiplicative_selection) {
    .Call('_GenomeAdmixR_simulate_cpp', PACKAGE = 'GenomeAdmixR', input_population, select, pop_size, number_of_founders, starting_proportions, total_runtime, morgan, progress_bar, track_frequency, track_markers, track_junctions, multiplicative_selection)
}

create_pop_admixed_cpp <- function(num_individuals, num_ancestors, population_size, size_in_morgan) {
    .Call('_GenomeAdmixR_create_pop_admixed_cpp', PACKAGE = 'GenomeAdmixR', num_individuals, num_ancestors, population_size, size_in_morgan)
}

test_fish_functions <- function() {
    invisible(.Call('_GenomeAdmixR_test_fish_functions', PACKAGE = 'GenomeAdmixR'))
}

